### ISSUE TITLE
Import issues 

### ISSUE THREAD

**Issue by DeanFeathers** [SebastianJarsve/Pythonista-Pixel-Editor#4]
Cant run the program as the imports are not specified and no instructions given on how to run the file or what is required. Please help

**Comment by SebastianJarsve** [comment]
@DeanFeathers 
It's fun to see that people are still interested in this project.
But I'm sorry to say that this isn't maintained anymore, and it hasn't been since 2014. I should probably add a note about it in the Readme.

But you're welcome to fork it and continue working on it if you want :)
